import { Bookmark, Check, Clock3, Copy, Download, ExternalLink, Eye, FileText, Heart, Link2, Send, Share2, ShieldAlert, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import api from "../services/api";
function formatBytes(bytes){if(!Number.isFinite(bytes)||bytes<=0)return"0 KB";const units=["B","KB","MB","GB"];const index=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),units.length-1);return`${(bytes/1024**index).toFixed(index===0?0:1)} ${units[index]}`;}
export default function PostDetail(){
  const {slug}=useParams();const {user}=useAuth();const [post,setPost]=useState(null);const [liked,setLiked]=useState(false);const [bookmarked,setBookmarked]=useState(false);const [comments,setComments]=useState([]);const [comment,setComment]=useState("");const [error,setError]=useState("");const [copied,setCopied]=useState(false);
  async function load(){try{const {data}=await api.get(`/posts/${slug}`);setPost(data.post);setLiked(data.liked);setBookmarked(data.bookmarked);const response=await api.get(`/comments/post/${data.post.id}`);setComments(response.data.comments);}catch(e){setError(e.message);}}
  useEffect(()=>{load();},[slug]);
  async function toggleLike(){if(!user)return setError("Please sign in to like this story.");const {data}=await api.post(`/posts/${post.id}/like`);setLiked(data.liked);setPost((current)=>({...current,_count:{...current._count,likes:data.count}}));}
  async function toggleBookmark(){if(!user)return setError("Please sign in to bookmark this story.");const {data}=await api.post(`/posts/${post.id}/bookmark`);setBookmarked(data.bookmarked);}
  async function copyUrl(){try{await navigator.clipboard.writeText(window.location.href);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{setError("Could not copy the URL.");}}
  async function sharePost(){if(navigator.share){try{await navigator.share({title:post.title,text:post.excerpt,url:window.location.href});return;}catch(e){if(e.name==="AbortError")return;}}await copyUrl();}
  async function submitComment(event){event.preventDefault();if(!user)return setError("Please sign in to comment.");if(!comment.trim())return;try{await api.post(`/comments/post/${post.id}`,{content:comment});setComment("");await load();}catch(e){setError(e.message);}}
  if(error&&!post)return <main className="page"><div className="empty-state"><h2>{error}</h2><Link to="/explore">Back to stories</Link></div></main>;if(!post)return<div className="page-loader">Loading story...</div>;
  return <main className="page article-page gradient-page">{post.isBlocked&&<div className="container moderation-owner-banner"><ShieldAlert size={20}/><div><strong>This post is blocked from public view.</strong><span>{post.blockedReason||"An administrator blocked this post."}</span></div></div>}<article><header className="article-header container narrow">{post.category&&<span className="category-pill static">{post.category.name}</span>}<h1>{post.title}</h1><p className="article-excerpt">{post.excerpt}</p><div className="article-author-row"><Link className="author-row author-link" to={`/profile/${post.author.id}`}><div className="avatar large">{post.author.name[0]}</div><div><strong>{post.author.name}</strong><span>{new Date(post.publishedAt||post.createdAt).toLocaleDateString()}</span></div></Link><div className="post-meta"><span><Clock3 size={16}/> {post.readTime} min read</span><span><Eye size={16}/> {post.viewCount}</span></div></div></header>
    <div className="container article-image-container"><img className="article-cover" src={post.coverImage||"https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1600&q=80"} alt={post.title}/></div>
    <div className="container article-layout"><aside className="article-actions"><button className={liked?"active":""} onClick={toggleLike}><Heart size={20} fill={liked?"currentColor":"none"}/><span>{post._count.likes}</span></button><button className={bookmarked?"active":""} onClick={toggleBookmark}><Bookmark size={20} fill={bookmarked?"currentColor":"none"}/></button><button onClick={sharePost}><Share2 size={20}/></button><button className={copied?"active":""} onClick={copyUrl}>{copied?<Check size={20}/>:<Copy size={20}/>}</button><Link to={`/communities?sharePost=${post.id}`} title="Share to community"><Users size={20}/></Link></aside>
      <div><div className="article-content" dangerouslySetInnerHTML={{__html:post.content}}/>{post.links?.length>0&&<section className="article-resource-section"><div className="resource-heading"><Link2/><div><span className="overline">Related URLs</span><h2>Links from this story</h2></div></div><div className="related-url-list">{post.links.map((link)=><a key={link.id} href={link.url} target="_blank" rel="noopener noreferrer"><div><strong>{link.label||"Related link"}</strong><span>{link.url}</span></div><ExternalLink size={18}/></a>)}</div></section>}{post.attachments?.length>0&&<section className="article-resource-section"><div className="resource-heading"><FileText/><div><span className="overline">Shared files</span><h2>Download attachments</h2></div></div><div className="attachment-download-grid">{post.attachments.map((file)=><a key={file.id} href={file.url} target="_blank" rel="noopener noreferrer" download><span className="attachment-download-icon"><FileText size={20}/></span><div><strong>{file.originalName}</strong><span>{formatBytes(file.size)} · {file.mimeType}</span></div><Download size={18}/></a>)}</div></section>}</div>
      <aside className="author-card interactive-surface"><Link to={`/profile/${post.author.id}`}><div className="avatar xlarge">{post.author.name[0]}</div><span className="overline">Written by</span><h3>{post.author.name}</h3></Link><p>{post.author.bio||"Writer and member of the BlogVerse community."}</p><Link className="button button-primary full" to={`/communities?sharePost=${post.id}`}><Users size={17}/> Share to community</Link><button className="button button-ghost full" onClick={sharePost}><Share2 size={17}/> Share story</button></aside>
    </div></article>
    <section className="comments-section"><div className="container narrow"><div className="section-heading compact"><div><span className="overline">Conversation</span><h2>{comments.length} Comments</h2></div></div><form className="comment-form" onSubmit={submitComment}><textarea value={comment} onChange={(e)=>setComment(e.target.value)} placeholder={user?"Add a thoughtful comment...":"Sign in to join the conversation"}/><button className="button button-primary" disabled={!user}><Send size={17}/> Comment</button></form>{error&&<div className="form-error">{error}</div>}{copied&&<div className="copy-toast"><Check size={16}/> Story URL copied</div>}<div className="comment-list">{comments.map((item)=><div className="comment interactive-surface" key={item.id}><Link className="avatar" to={`/profile/${item.user.id}`}>{item.user.name[0]}</Link><div><strong>{item.user.name}</strong><span>{new Date(item.createdAt).toLocaleDateString()}</span><p>{item.content}</p></div></div>)}</div></div></section>
  </main>;
}
